image: microsoft/dotnet:latest

stages:
    - build
    
before_script:
    - "curl -sL https://deb.nodesource.com/setup_10.x | bash -"
    - "apt-get install -y nodejs"
    - "cd Energize.Web/ClientApp"
    - "npm install Energize.Web/ClientApp"
    - "cd ./.."
    - "dotnet restore"

build:
    stage: build
    script:
        - "dotnet build Energize.Web"
